### ISSUE TITLE
Exception when preempting policy execution

### ISSUE THREAD

**Issue by hawesie** [bfalacerda/strands_executive#11]
I think I was preempting during the last action in the policy.

```
[ERROR] [WallTime: 1460300320.960512] Exception in your execute callback: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/opt/ros/indigo/lib/python2.7/site-packages/actionlib/simple_action_server.py", line 299, in executeLoop
    self.execute_callback(goal)
  File "/Users/nah/code/indigo_ws/src/strands_executive/mdp_plan_exec/scripts/mdp_policy_executor_extended.py", line 199, in execute_policy_cb
    (status, state_update)=self.action_executor.execute_action(self.current_extended_mdp.action_descriptions[next_action])
TypeError: 'NoneType' object is not iterable
```

**Comment by bfalacerda** [comment]
https://github.com/bfalacerda/strands_executive/commit/d1f86e6c960de166a722618eff6fd484bc7288d5 should solve this

**Comment by hawesie** [comment]
Ok, I'll close this as it only occurred in an odd situation.

**Comment by bfalacerda** [comment]
and it wont happen again! ;)
